services:
  - docker

# Todo: automate this
script:
  # PHP 5.6
  - docker build 5.6/alpine/bcmath
  - docker build 5.6/alpine/mongo
  - docker build 5.6/alpine/pcntl
  # PHP 7.1
  - docker build 7.1/alpine/gd
  - docker build 7.1/alpine/intl
  - docker build 7.1/alpine/mcrypt
  - docker build 7.1/alpine/memcached
  - docker build 7.1/alpine/opcache
  - docker build 7.1/alpine/pdo_mysql
  - docker build 7.1/alpine/soap
  - docker build 7.1/alpine/zip
  - docker build 7.1/alpine/xdebug

branches:
  only:
    - master
