services:
  - docker

# Todo: automate this
script:
  - docker build gd/alpine -t lucasvanlierop/php-gd-alpine && docker run --rm lucasvanlierop/php-gd-alpine php -r "if (extension_loaded('gd') === false) exit(1);"

branches:
  only:
    - master
